import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//Layout is also a special type of file, which is a shell for pages = pages will be rendered inside the layout

//Some reserved file names of NextJS:
// - layout
// - page
// - global.css global styles (directly in /app)
// - icon favicon and browser page icon (directly in /app)

const inter = Inter({ subsets: ["latin"] });

//head tag is generated based on the MetaData object
export const metadata: Metadata = {
  title: "Essentials",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
