services:
  front:
    build:
      dockerfile: ./front.Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - back
    environment:
      - FRONT_PORT=9090

  back:
    build:
      dockerfile: ./back.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:9090
      - REDIS_HOST=24-redis-1

  redis:
    image: redis:6.2.12-bullseye
    restart: unless-stopped
    volumes:
      - redis:/data

volumes:
  redis: