services:
  front:
    build:
      dockerfile: ./front.Dockerfile
    ports:
      - 9090:9090
    environment:
      - FRONT_PORT=9090

  back:
    build:
      dockerfile: ./back.Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:9090