services:
  proxy:
    build: .
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - ./public:/usr/local/nginx/public

networks:
  backend:
    name: altzone_backend